services:
  whisper-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisper-gpu
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      MODEL: "large-v3"
      DEVICE: "cuda"
      COMPUTE_TYPE: "float16"
      LANGUAGE: "ru"
      CUDA_VISIBLE_DEVICES: "2"   # ← внутри контейнера будет видна только физическая GPU2 (#3)
      PROMPT_FILE: "/whisper_server/custom_prompt.txt"
    ports:
      - "8001:8000"
    volumes:
      - whisper_models:/models
    networks:
      - local_net
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  whisper_models:

networks:
  local_net:
    external: true
